export type Difficulty = 'easy' | 'medium' | 'hard';

export const CONFIG = {
  world: { width: 3000, height: 3000 },
  canvas: { backgroundColor: '#101418' },
  camera: { moveSpeed: 520, minZoom: 0.4, maxZoom: 2.5 },
  grid: { cellSize: 80 },
  units: {
    player: {
      knight: {
        hp: 60,
        damage: 14,
        attackRange: 30,
        attackCooldown: 0.55,
        speed: 150,
        searchRadius: 140,
        radius: 7,
        color: '#38b6ff',
      },
      archer: {
        hp: 40,
        damage: 11,
        attackRange: 150,
        attackCooldown: 0.8,
        speed: 140,
        searchRadius: 260,
        radius: 6,
        color: '#4ec2ff',
      },
      tank: {
        hp: 140,
        damage: 9,
        attackRange: 26,
        attackCooldown: 0.75,
        speed: 95,
        searchRadius: 110,
        radius: 9,
        color: '#2ea8ff',
      },
      champion: {
        hp: 220,
        damage: 26,
        attackRange: 36,
        attackCooldown: 0.8,
        speed: 120,
        searchRadius: 150,
        radius: 11,
        color: '#ffd166',
      },
      boss: {
        hp: 6500,
        damage: 34,
        attackRange: 34,
        attackCooldown: 1.4,
        speed: 55,
        searchRadius: 240,
        radius: 30,
        color: '#c0392b',
      },
    },
    enemy: {
      knight: {
        hp: 40,
        damage: 9,
        attackRange: 24,
        attackCooldown: 0.7,
        speed: 90,
        searchRadius: 100,
        radius: 7,
        color: '#ff4655',
      },
      archer: {
        hp: 28,
        damage: 8,
        attackRange: 150,
        attackCooldown: 1.1,
        speed: 100,
        searchRadius: 240,
        radius: 6,
        color: '#ff8fa3',
      },
      tank: {
        hp: 120,
        damage: 7,
        attackRange: 20,
        attackCooldown: 1,
        speed: 60,
        searchRadius: 110,
        radius: 9,
        color: '#e0563f',
      },
      champion: {
        hp: 180,
        damage: 16,
        attackRange: 30,
        attackCooldown: 0.9,
        speed: 85,
        searchRadius: 130,
        radius: 10,
        color: '#ffb04d',
      },
      boss: {
        hp: 6500,
        damage: 34,
        attackRange: 34,
        attackCooldown: 1.4,
        speed: 55,
        searchRadius: 240,
        radius: 30,
        color: '#c0392b',
      },
    },
  },
  recruits: {
    knight: { count: 5, cost: 10, icon: '⚔️' },
    archer: { count: 5, cost: 15, icon: '🏹' },
    tank: { count: 5, cost: 20, icon: '🛡️' },
    champion: { count: 1, cost: 50, icon: '⭐' },
  },
  separation: { radius: 16, strength: 70 },
  selection: { dragThreshold: 5, pickRadius: 9, spacing: 20 },
  formation: {
    tick: 0.4,
    frontDepth: 1.6,
    eliteDepth: 0.5,
    backDepth: 2.2,
    holdLeash: 70,
    idleLeash: 12,
    threatRadius: 900,
  },
  base: { hp: 1000, radius: 42, color: '#3ddc84' },
  castle: {
    wallHalf: 260,
    wallThickness: 18,
    wallHp: 250,
    wallColor: '#7b8591',
    gateWidth: 96,
    segmentsPerSide: 4,
    towerRadius: 24,
    towerHp: 400,
    towerDamage: 14,
    towerRange: 300,
    towerCooldown: 1.1,
    towerColor: '#8f9baa',
    mineOffset: 130,
  },
  mine: { hp: 400, radius: 26, goldPerSecond: 0.5, color: '#ffd166' },
  boss: {
    name: 'SENHOR DA RUÍNA',
    defense: 0.5,
    aggroRadius: 360,
    smashRange: 200,
    abilityDamage: 55,
    abilityRadius: 165,
    abilityTriggerRange: 220,
    abilityCooldown: 9,
    abilityTelegraph: 1.1,
    abilityImpact: 0.35,
  },
  projectiles: { arrowSpeed: 520, maxLife: 2.5, hitRadius: 10 },
  story: {
    cart: { hp: 400, radius: 26, speed: 50, color: '#e8b96a' },
  },
  economy: {
    startingGold: 120,
    passiveGoldPerSecond: 0.5,
    killReward: 2,
  },
  progression: {
    castle: {
      maxLevel: 5,
      costs: [200, 400, 800, 1500] as readonly number[],
      hpBonus: [0, 250, 500, 900, 1500] as readonly number[],
      towerCooldown: [1, 0.85, 0.72, 0.6, 0.5] as readonly number[],
      buildingCap: [6, 10, 16, 22, 30] as readonly number[],
    },
    troops: {
      maxLevel: 3,
      knight: {
        costs: [100, 250] as readonly number[],
        costsDiamond: false,
        hp: [1, 1.3, 1.6] as readonly number[],
        damage: [1, 1.3, 1.65] as readonly number[],
        speed: [1, 1.08, 1.15] as readonly number[],
        attackSpeed: [1, 1, 1] as readonly number[],
        range: [1, 1, 1] as readonly number[],
        defense: [0, 0, 0] as readonly number[],
      },
      archer: {
        costs: [100, 250] as readonly number[],
        costsDiamond: false,
        hp: [1, 1, 1] as readonly number[],
        damage: [1, 1.25, 1.5] as readonly number[],
        speed: [1, 1, 1] as readonly number[],
        attackSpeed: [1, 1.12, 1.25] as readonly number[],
        range: [1, 1.15, 1.3] as readonly number[],
        defense: [0, 0, 0] as readonly number[],
      },
      tank: {
        costs: [150, 350] as readonly number[],
        costsDiamond: false,
        hp: [1, 1.4, 1.8] as readonly number[],
        damage: [1, 1.2, 1.4] as readonly number[],
        speed: [1, 1, 1] as readonly number[],
        attackSpeed: [1, 1, 1] as readonly number[],
        range: [1, 1, 1] as readonly number[],
        defense: [0, 0.15, 0.25] as readonly number[],
      },
      champion: {
        costs: [1, 1] as readonly number[],
        costsDiamond: true,
        hp: [1, 1.25, 1.5] as readonly number[],
        damage: [1, 1.4, 1.8] as readonly number[],
        speed: [1, 1.05, 1.12] as readonly number[],
        attackSpeed: [1, 1, 1] as readonly number[],
        range: [1, 1, 1] as readonly number[],
        defense: [0, 0, 0] as readonly number[],
      },
    },
    diamonds: { everyWaves: 15 },
    buildings: {
      baseTroopCap: 50,
      house: { cost: 60, troopCapBonus: 10, hp: 250, radius: 18 },
      market: { cost: 120, goldPerSecond: 200 / 60, hp: 300, radius: 20 },
      tower: { cost: 500, hp: 500, radius: 20, damage: 25, range: 320 },
    },
    noBuild: {
      infinite: [] as { x1: number; y1: number; x2: number; y2: number; width: number }[],
      adventure: [{ x1: 800, y1: 3200, x2: 3200, y2: 800, width: 60 }],
    },
  },
  player: { startingTroops: { knight: 3, archer: 2, tank: 1 } },
  adventure: {
    worldW: 4000,
    worldH: 4000,
    playerBase: { x: 800, y: 3200 },
    enemyBase: { x: 3200, y: 800 },
    baseHp: 1500,
    enemyBaseHp: 1500,
    startingGold: 80,
    passiveGoldPerSecond: 0.3,
    troopCap: 50,
    startingKnights: 5,
    fogCellSize: 160,
    revealRadius: 260,
    revealSpeed: 3.2,
    capture: { radius: 90, time: 2 },
    defenders: { knights: 8, archers: 3, tanks: 2, ringRadius: 120, searchRadius: 340 },
  },
  waves: {
    prepTime: 30,
    baseCount: 5,
    growth: 1.5,
    maxPerWave: 100,
    spawnStagger: 0.12,
    clusterSize: 6,
    clusterRadius: 45,
    hpGrowth: 0.08,
    hpCap: 4,
    damageGrowth: 0.05,
    damageCap: 3,
    speedGrowth: 0.015,
    speedCap: 1.6,
    rangeGrowth: 0.01,
    rangeCap: 1.5,
    cooldownGrowth: 0.03,
    cooldownMin: 0.35,
    clearBonusBase: 15,
    clearBonusPerWave: 5,
  },
  difficulty: {
    easy: {
      enemyScaling: 0.85,
      spawnScaling: 0.7,
      compositionScaling: 0.8,
      defenseGrowth: 0,
    },
    medium: {
      enemyScaling: 1,
      spawnScaling: 1,
      compositionScaling: 1,
      defenseGrowth: 0,
    },
    hard: {
      enemyScaling: 1.15,
      spawnScaling: 1.3,
      compositionScaling: 1.2,
      defenseGrowth: 0.005,
    },
  },
  ui: {
    moveMarkerDuration: 0.5,
    recruitMarkerDuration: 0.7,
    deniedMarkerDuration: 0.9,
    goldGainThreshold: 0.5,
    hitFlashDuration: 0.14,
    hitMarkerDuration: 0.28,
    damageMarkerDuration: 0.65,
    deathMarkerDuration: 0.4,
    toastDuration: 1.7,
    maxMarkers: 220,
    maxDamageMarkers: 90,
    countdownWarnAt: 10,
    prepareMusicFactor: 0.72,
    screenTransition: 0.16,
    menuEmbers: 26,
    menuDust: 14,
  },
  positions: {
    base: { x: 1500, y: 1500 },
    enemySpawns: [
      { x: 150, y: 150 },
      { x: 2850, y: 150 },
      { x: 150, y: 2850 },
      { x: 2850, y: 2850 },
      { x: 1500, y: 100 },
      { x: 1500, y: 2900 },
      { x: 100, y: 1500 },
      { x: 2900, y: 1500 },
    ],
  },
} as const;